<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Schema;

/**
 * The append-only audit log.
 *
 * Deliberately missing: `updated_at`, a soft-delete column, and any foreign key
 * into `users`. The first two are the shape of a mutable row; the third would
 * let a user deletion cascade away the record of what that user did, which is
 * precisely the record an incident review needs. `actor_label` is denormalised
 * for the same reason — the log has to survive a rename.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('audit_entries', function (Blueprint $table): void {
            // Generated by the writer, never by the database: a ULID sorts by
            // creation time and needs no sequence, so concurrent writers do not
            // contend over one.
            $table->char('id', 26)->primary();

            $table->timestamp('occurred_at', 3)->useCurrent();

            // A string, not a foreign id: an actor may be a numeric user id
            // today and a ULID-keyed service tomorrow, and there is no FK to
            // cascade regardless.
            $table->string('actor_id', 64)->nullable();
            $table->string('actor_type', 32);
            $table->string('actor_label', 255);

            $table->string('action', 64);
            $table->string('target_type', 64)->nullable();
            $table->string('target_id', 64)->nullable();

            $table->json('before')->nullable();
            $table->json('after')->nullable();

            // 45 characters: the longest IPv6 form, including an embedded IPv4.
            $table->string('source_ip', 45)->nullable();
            $table->char('request_id', 26)->nullable();

            // Every index is (something, occurred_at) because every question
            // asked of an audit log is bounded in time: "what did this person
            // do LAST WEEK", never "what did this person ever do".
            $table->index('occurred_at');
            $table->index(['actor_id', 'occurred_at']);
            $table->index(['action', 'occurred_at']);
            $table->index(['target_type', 'target_id']);
        });

        $this->revokeWriteGrants();
    }

    public function down(): void
    {
        Schema::dropIfExists('audit_entries');
    }

    /**
     * Best-effort second lock at the database role level.
     *
     * Guarded and swallowed on purpose: hosted databases routinely deny GRANT
     * OPTION to the application role, and a deploy that fails for that reason
     * would be a worse outcome than an audit table protected only by the
     * application. Idempotent — re-running against an already-revoked grant is
     * a no-op or an error we swallow either way.
     */
    private function revokeWriteGrants(): void
    {
        if (! config('audit.revoke_write_grants', true)) {
            return;
        }

        $driver = DB::getDriverName();

        // SQLite has no grant system at all, and the test suite runs on it.
        if ($driver === 'sqlite') {
            return;
        }

        try {
            $username = DB::getConfig('username');

            if (! is_string($username) || $username === '') {
                return;
            }

            // Quoted as an identifier, not interpolated: the username comes
            // from configuration, and configuration is not a trusted literal.
            $quoted = str_replace('"', '""', $username);

            DB::unprepared(sprintf('REVOKE UPDATE, DELETE ON audit_entries FROM "%s"', $quoted));
        } catch (Throwable $e) {
            Log::warning('audit.revoke_write_grants failed', [
                'exception' => $e->getMessage(),
                'detail' => 'The application-level immutability guarantees still hold.',
            ]);
        }
    }
};
