import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

import { describe, expect, it } from "vitest";

/**
 * Every component can be reached from a route.
 *
 * A screen nobody can navigate to is not a feature that is nearly finished —
 * it is a feature that does not exist, wearing a green tick. `NewTicketScreen`
 * was written in full, given its own test, and marked done; no file under
 * `app/` ever imported it, so for two stories an agent could not open a ticket
 * from the application at all. `StaleVersionBanner` had the same shape: built,
 * tested, marked done, mounted nowhere, and quietly reimplemented inside
 * another component.
 *
 * Nothing caught either one because a component test renders the component. It
 * proves the piece works. It says nothing about whether anybody can get to it,
 * and "can" is what a Done Criterion written in the user's voice actually
 * promises.
 *
 * So this walks the import graph outward from `app/` — the only real entry
 * points — and asks which components the walk never arrives at.
 *
 * The walk is transitive on purpose. `app/(app)/page.tsx` imports
 * `AgentHomePage`, which imports `AgentHomeScreen`, which imports
 * `CountsStrip`. Checking one level would flag all three.
 */

const ROOT = resolve(__dirname, "../..");

/**
 * Vendored primitives, excluded deliberately.
 *
 * `components/ui/` is generated by shadcn's CLI, which drops in a whole
 * primitive when you ask for one. An unused Radix wrapper is inert markup, not
 * an unreachable feature — and failing the build over one would push people to
 * stop adding primitives ahead of the screen that needs them. Everything ABOVE
 * that layer is somebody's intent, and unreachable intent is the bug.
 */
const EXCLUDED = ["components/ui/"];

function filesUnder(dir: string, out: string[] = []): string[] {
  if (!existsSync(dir)) return out;

  for (const entry of readdirSync(dir)) {
    if (entry === "node_modules" || entry === ".next") continue;

    const full = join(dir, entry);

    if (statSync(full).isDirectory()) filesUnder(full, out);
    else if (/\.tsx?$/.test(full)) out.push(full);
  }

  return out;
}

const SUFFIXES = ["", ".tsx", ".ts", "/index.tsx", "/index.ts"];

/** Resolves `@/…` and relative specifiers the way the bundler does. */
function fileFor(specifier: string, importer: string): string | null {
  let base: string;

  if (specifier.startsWith("@/")) base = join(ROOT, specifier.slice(2));
  else if (specifier.startsWith(".")) base = resolve(dirname(importer), specifier);
  else return null; // A package, not our code.

  for (const suffix of SUFFIXES) {
    const candidate = base + suffix;

    if (existsSync(candidate) && statSync(candidate).isFile()) return candidate;
  }

  return null;
}

/*
 * Static imports, re-exports, and `import()`. Dynamic `import()` matters:
 * `TicketDetailPage` reaches the API client that way, and treating it as
 * nothing would report half the graph as unreachable.
 */
const SPECIFIER =
  /(?:^|\n)\s*(?:import|export)[\s\S]*?from\s*["']([^"']+)["']|import\s*\(\s*["']([^"']+)["']\s*\)/g;

function importsOf(file: string): string[] {
  const source = readFileSync(file, "utf8");
  const found = new Set<string>();

  SPECIFIER.lastIndex = 0;

  let match: RegExpExecArray | null;

  while ((match = SPECIFIER.exec(source)) !== null) {
    const specifier = match[1] ?? match[2];

    if (specifier === undefined) continue;

    const target = fileFor(specifier, file);

    if (target !== null) found.add(target);
  }

  return [...found];
}

function reachableFromRoutes(): Set<string> {
  const seen = new Set<string>();
  const queue = filesUnder(join(ROOT, "app"));

  while (queue.length > 0) {
    const file = queue.pop();

    if (file === undefined || seen.has(file)) continue;

    seen.add(file);
    queue.push(...importsOf(file));
  }

  return seen;
}

function unreachable(): string[] {
  const reached = reachableFromRoutes();

  return filesUnder(join(ROOT, "components"))
    .filter((file) => !reached.has(file))
    .map((file) => relative(ROOT, file))
    .filter((path) => !EXCLUDED.some((prefix) => path.startsWith(prefix)))
    .sort();
}

describe("the component graph", () => {
  it("has no screen that a route cannot reach", () => {
    const orphans = unreachable().filter((path) => path.startsWith("components/screens/"));

    expect(orphans).toEqual([]);
  });

  it("has no component of any kind that a route cannot reach", () => {
    /*
     * Wider than screens, and deliberately not softened into a warning. A
     * component with no caller is either work nobody can use or work somebody
     * already redid somewhere else — and both of those are worth a failing
     * test rather than a note in a file.
     */
    expect(unreachable()).toEqual([]);
  });

  it("actually walks the graph rather than finding nothing", () => {
    /*
     * Guarding the guard. Every assertion above passes trivially if the walk
     * is broken — a resolver that returns null for everything would report a
     * clean graph. So: a component known to sit three hops from a route must
     * come out reachable.
     */
    const reached = reachableFromRoutes();

    expect(reached.has(join(ROOT, "components/screens/home/CountsStrip.tsx"))).toBe(true);
    expect(reached.has(join(ROOT, "components/domain/DataTable/DataTable.tsx"))).toBe(true);
  });

  it("reports a file nothing imports", () => {
    // And the other direction: the walk must not claim to reach a path that
    // does not exist at all.
    const reached = reachableFromRoutes();

    expect(reached.has(join(ROOT, "components/screens/nothing/Invented.tsx"))).toBe(false);
  });
});
